### ISSUE TITLE
To-Do Module (Client-Specific Page V.1.0)

### ISSUE THREAD

**Issue by colecoleman** [colecoleman/spin-dj-app#29]
Admin-set to-dos per client with ability to cross off, and show completed items at bottom with a success message when all are done. 

- [x] show list of uncompleted and completed to-dos,
- [ ] store to-dos in admin's data profile
- [ ] show to-dos only for specific client by querying against data
- [ ] add to-do
- [x] allow user to check off with strikethrough animation
- [x] show success message when no uncompleted are present
